version: "3.8"

services:
  notifications:
    build: ./
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always
    ports:
      - "8004:8000"
    depends_on:
      - kafka
      - postgres
    networks:
      - default
      - shared_network

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker_volumes/pg_volume:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    volumes:
      - ./docker_volumes/zookeeper_data:/bitnami/zookeeper
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=yes
      - KAFKA_CREATE_TOPICS=user.events:1:1,post.events:1:1,comments.events:1:1,notification.events:1:1
    volumes:
      - ./docker_volumes/kafka_volume:/bitnami/kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    restart: unless-stopped
    networks:
      - default
      - shared_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
      KAFKA_CLUSTERS_0_ZOOKEEPER: 'zookeeper:2181'
    ports:
      - '8080:8080'
    restart: unless-stopped
    networks:
      - default
      - shared_network

  kafka-exporter:
    image: danielqsj/kafka-exporter
    command:
      - "--kafka.server=kafka:9092"
    depends_on:
      - kafka
    restart: on-failure
    ports:
      - 9308:9308
    networks:
      - default
      - shared_network


networks:
  shared_network:
    external: true
