services:

  api-gateway:
    build: ./
    container_name: api-gateway
    ports:
      - "80:80"
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./lua:/usr/local/openresty/nginx/lua/
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./proxy_headers.conf:/usr/local/openresty/nginx/conf/proxy_headers.conf
    networks:
      - default
      - shared_network

networks:
  shared_network:
    external: true
