"""empty message

Revision ID: 534392a0a2c2
Revises: 
Create Date: 2025-04-10 13:16:16.445874

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '534392a0a2c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('media_type', sa.Enum('photo', 'video', name='media_type'), nullable=False),
                    sa.Column('exif_metadata', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
                    )
    op.create_table('storage_bucket',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.Column('storage_class', sa.String(length=12), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_bucket')),
                    sa.UniqueConstraint('name', name=op.f('uq_storage_bucket_name'))
                    )
    op.create_table('media_representation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('media_id', sa.UUID(), nullable=False),
                    sa.Column('variant', sa.String(length=16), nullable=False),
                    sa.Column('s3_key', sa.String(length=128), nullable=False),
                    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
                    sa.Column('hash', sa.String(length=1024), nullable=False),
                    sa.Column('hash_type', sa.String(length=10), nullable=False),
                    sa.Column('bucket_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['bucket_id'], ['storage_bucket.id'],
                                            name=op.f('fk_media_representation_bucket_id_storage_bucket')),
                    sa.ForeignKeyConstraint(['media_id'], ['media.id'],
                                            name=op.f('fk_media_representation_media_id_media')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_representation'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_representation')
    op.drop_table('storage_bucket')
    op.drop_table('media')
    # ### end Alembic commands ###
