{
 "title": "Loki stack monitoring (Promtail, Loki)",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. Shows: some error metrics published by Promtail/Loki. Error and warning logs emitted by Promtail/Loki. Memory and CPU usage of Promtail/Loki compared against the Kubernetes memory/cpu limits and requests.",
 "tags": [
  "tools",
  "loki"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource Prometheus", "query": "prometheus" },
   { "name": "datasource", "label": "Datasource Loki", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Summary of alerts status", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  { "title": "Problems in the Loki Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Number of error/warning messages logged by Loki itself",
   "type": "graph",
   "description": "Total number of messages logged by Loki itself",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_messages_total{app=\"loki\",level=~\"error|warn\"}[1m])) by (level)\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Loki itself",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"loki\"} | logfmt | level=\"warn\" or level=\"error\""
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "graph",
   "description": "Total number of messages logged by Promtail",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_messages_total{app_kubernetes_io_name=\"promtail\",level=~\"error|warn\"}[1m])) by (level)\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "{app=\"promtail\"} | logfmt | level=\"warn\" or level=\"error\""
    }
   ]
  },
  {
   "title": "Loki (distributor) - failed batch appends sent to ingesters",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_append_failures_total[1m])*60"
    }
   ]
  },
  {
   "title": "Promtail - dropped log entries",
   "type": "graph",
   "description": "Number of log entries dropped because failed to be sent to the Loki ingester after all retries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promtail_dropped_entries_total[1m])*60",
     "legendFormat": "pod={{kubernetes_pod_name}}, instance={{instance}}"
    }
   ]
  },
  { "title": "Logging activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of Streams in Loki",
   "type": "graph",
   "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loki_ingester_memory_streams", "legendFormat": "Streams" }
   ]
  },
  {
   "title": "Loki (distributor) - log entries received per second",
   "type": "graph",
   "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1m])"
    }
   ]
  },
  {
   "title": "Bytes received in ingester per second",
   "type": "graph",
   "description": "The total number of uncompressed bytes received per tenant.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Loki memory usage (% of Kubernetes memory limit)",
   "type": "graph",
   "description": "Percentage of actual usage over configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * max by(pod,container) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"loki.*\"})\n/\non (pod,container) group_left  kube_pod_container_resource_limits_memory_bytes{pod=~\"loki.*\"}",
     "legendFormat": "Usage (pod={{pod}}, container={{container}}, name={{name}})"
    }
   ]
  },
  {
   "title": "Loki memory usage vs Kubernetes limit and request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}",
     "legendFormat": "Usage (pod={{pod}}, container={{container}})"
    },
    {
     "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"loki.*\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"loki.*\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Promtail memory usage (% of Kubernetes memory limit)",
   "type": "graph",
   "description": "Percentage of actual usage over configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100* max by(pod,container) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"})\n/\non (pod,container) (kube_pod_container_resource_limits_memory_bytes{pod=~\"promtail.*\"})"
    }
   ]
  },
  {
   "title": "Promtail memory usage vs Kubernetes limit and request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}",
     "legendFormat": "Usage (pod={{pod}}, container={{container}})"
    },
    {
     "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"promtail.*\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"promtail.*\"})",
     "legendFormat": "Request"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Loki CPU usage (% of Kubernetes CPU limit)",
   "type": "graph",
   "description": "percentage of configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "100* rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",pod=~\"loki.*\"}[1m])\n/\non (pod,container) kube_pod_container_resource_limits_cpu_cores{container=\"loki\"}"
    }
   ]
  },
  {
   "title": "Loki CPU usage vs Kubernetes limit and request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}[1m])",
     "legendFormat": "CPU Usage (pod={{pod}}, container={{container}})"
    },
    {
     "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"loki.*\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"loki.*\"})",
     "legendFormat": "CPU Request"
    }
   ]
  },
  {
   "title": "Promtail CPU usage (% of Kubernetes limit)",
   "type": "graph",
   "description": "percentage of configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}[1m])\n/\non (pod,container) kube_pod_container_resource_limits_cpu_cores{pod=~\"promtail.*\"}"
    }
   ]
  },
  {
   "title": "Promtail CPU usage vs Kubernetes limit and request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}[1m])",
     "legendFormat": "CPU Usage (pod={{pod}}, container={{container}})"
    },
    {
     "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"promtail.*\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"promtail.*\"})",
     "legendFormat": "CPU Request"
    }
   ]
  }
 ]
}