global:
  scrape_interval: 15s  # как часто собирать метрики
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'content-processor'
    static_configs:
        - targets: [ 'fastapi:8001' ]

  - job_name: 'notifications'
    static_configs:
      - targets: [ 'fastapi:8004' ]

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka:7071' ]

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]
  - job_name: 'nginx'
    static_configs:
      - targets: [ 'api-gateway:80' ]

  # Пример для node_exporter, если он есть
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
