services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8002:${SERVICE_PORT}"
    env_file:
      - ./configs/.env
    depends_on:
      - db
    networks:
      - default
      - shared_network

  db:
    image: postgres:17-alpine
    container_name: events_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./configs/.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./internal/repository/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data

networks:
  shared_network:
    external: true