version: "3.8"

services:

  fastapi:
    build: ./
    container_name: fastapi
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head && python3 init_storages.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    networks:
      - postgres_network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - postgres_network
    ports:
      - "5434:5432"
    restart: unless-stopped


volumes:
  pg_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker_volumes/pg_volume
  redis_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker_volumes/redis_volume



networks:
  postgres_network:
    driver: bridge